-- Insert Multi-Country Payroll Settings
-- This script adds payroll settings for all 6 countries (other than India) to HRMS_PAYROLL_SETTINGS table

-- First, ensure the PAYROLL_COUNTRY column exists
-- ALTER TABLE HRMS_PAYROLL_SETTINGS ADD PAYROLL_COUNTRY VARCHAR2(3) DEFAULT 'IND';

-- Update existing India records to have country code
UPDATE HRMS_PAYROLL_SETTINGS 
SET PAYROLL_COUNTRY = 'IND' 
WHERE PAYROLL_COUNTRY IS NULL OR PAYROLL_COUNTRY = '';

-- Commit the update
COMMIT;

-- ================================
-- UAE (United Arab Emirates) Settings
-- ================================

-- UAE General Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'currency', 'AED', 'STRING', 'UAE Dirham currency code', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payFrequency', 'MONTHLY', 'STRING', 'Pay frequency for UAE employees', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payDay', '25', 'NUMBER', 'Default pay day for UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingDaysPerWeek', '6', 'NUMBER', 'Working days per week in UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingHoursPerDay', '8', 'NUMBER', 'Standard working hours per day in UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'ramadanWorkingHours', '6', 'NUMBER', 'Working hours during Ramadan in UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeEnabled', 'true', 'BOOLEAN', 'Overtime calculation enabled for UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeRate', '1.25', 'NUMBER', 'UAE overtime rate (125%)', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'holidayPayEnabled', 'true', 'BOOLEAN', 'Holiday pay enabled for UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'holidayPayRate', '1.5', 'NUMBER', 'UAE holiday pay rate (150%)', 'UAE', 1, 1);

-- UAE Compliance Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'wpsEnabled', 'true', 'BOOLEAN', 'WPS enabled for UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'wpsEstablishmentId', '', 'STRING', 'WPS Establishment ID for UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'tradeLicenseNumber', '', 'STRING', 'Trade License Number for UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'mohreEstablishmentCard', '', 'STRING', 'MOHRE Establishment Card Number', 'UAE', 1, 1);

-- UAE Leave Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'annualLeaveDays', '30', 'NUMBER', 'Annual leave days in UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'sickLeaveDays', '90', 'NUMBER', 'Sick leave days in UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'maternityLeaveDays', '45', 'NUMBER', 'Maternity leave days in UAE', 'UAE', 1, 1);

-- ================================
-- SAUDI ARABIA Settings
-- ================================

-- Saudi General Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'currency', 'SAR', 'STRING', 'Saudi Riyal currency code', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payFrequency', 'MONTHLY', 'STRING', 'Pay frequency for Saudi employees', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payDay', '25', 'NUMBER', 'Default pay day for Saudi Arabia', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingDaysPerWeek', '6', 'NUMBER', 'Working days per week in Saudi Arabia', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingHoursPerDay', '8', 'NUMBER', 'Standard working hours per day in Saudi Arabia', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'ramadanWorkingHours', '6', 'NUMBER', 'Working hours during Ramadan in Saudi Arabia', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeEnabled', 'true', 'BOOLEAN', 'Overtime calculation enabled for Saudi Arabia', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeRate', '1.5', 'NUMBER', 'Saudi Arabia overtime rate (150%)', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'holidayPayEnabled', 'true', 'BOOLEAN', 'Holiday pay enabled for Saudi Arabia', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'holidayPayRate', '1.5', 'NUMBER', 'Saudi Arabia holiday pay rate (150%)', 'SAU', 1, 1);

-- Saudi Compliance Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'wpsEnabled', 'true', 'BOOLEAN', 'MUDAWALA WPS enabled for Saudi Arabia', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'mudawalaEstablishmentId', '', 'STRING', 'MUDAWALA Establishment ID', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'commercialRegistration', '', 'STRING', 'Commercial Registration Number', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'molEstablishmentNumber', '', 'STRING', 'Ministry of Labor Establishment Number', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'gosiNumber', '', 'STRING', 'GOSI Registration Number', 'SAU', 1, 1);

-- Saudi Leave Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'annualLeaveDays', '21', 'NUMBER', 'Annual leave days in Saudi Arabia (increases to 30 after 5 years)', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'sickLeaveDays', '120', 'NUMBER', 'Sick leave days in Saudi Arabia', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'maternityLeaveDays', '70', 'NUMBER', 'Maternity leave days in Saudi Arabia', 'SAU', 1, 1);

-- ================================
-- OMAN Settings
-- ================================

-- Oman General Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'currency', 'OMR', 'STRING', 'Omani Rial currency code', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payFrequency', 'MONTHLY', 'STRING', 'Pay frequency for Oman employees', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payDay', '25', 'NUMBER', 'Default pay day for Oman', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingDaysPerWeek', '6', 'NUMBER', 'Working days per week in Oman', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingHoursPerDay', '8', 'NUMBER', 'Standard working hours per day in Oman', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'ramadanWorkingHours', '6', 'NUMBER', 'Working hours during Ramadan in Oman', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeEnabled', 'true', 'BOOLEAN', 'Overtime calculation enabled for Oman', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeRate', '1.25', 'NUMBER', 'Oman daytime overtime rate (125%)', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'nightOvertimeRate', '1.5', 'NUMBER', 'Oman nighttime overtime rate (150%)', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'holidayOvertimeRate', '2.0', 'NUMBER', 'Oman holiday overtime rate (200%)', 'OMN', 1, 1);

-- Oman Compliance Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'wpsEnabled', 'true', 'BOOLEAN', 'WPS enabled for Oman', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'pasiNumber', '', 'STRING', 'PASI Registration Number', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'commercialRegistration', '', 'STRING', 'Commercial Registration Number for Oman', 'OMN', 1, 1);

-- Oman Leave Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'annualLeaveDays', '30', 'NUMBER', 'Annual leave days in Oman', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'sickLeaveDays', '30', 'NUMBER', 'Sick leave days in Oman', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'maternityLeaveDays', '50', 'NUMBER', 'Maternity leave days in Oman', 'OMN', 1, 1);

-- ================================
-- BAHRAIN Settings
-- ================================

-- Bahrain General Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'currency', 'BHD', 'STRING', 'Bahraini Dinar currency code', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payFrequency', 'MONTHLY', 'STRING', 'Pay frequency for Bahrain employees', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payDay', '25', 'NUMBER', 'Default pay day for Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingDaysPerWeek', '6', 'NUMBER', 'Working days per week in Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingHoursPerDay', '8', 'NUMBER', 'Standard working hours per day in Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'ramadanWorkingHours', '6', 'NUMBER', 'Working hours during Ramadan in Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeEnabled', 'true', 'BOOLEAN', 'Overtime calculation enabled for Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeRate', '1.25', 'NUMBER', 'Bahrain regular overtime rate (125%)', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'restDayOvertimeRate', '1.5', 'NUMBER', 'Bahrain rest day overtime rate (150%)', 'BHR', 1, 1);

-- Bahrain Compliance Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'wpsEnabled', 'true', 'BOOLEAN', 'WPS enabled for Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'gosiNumber', '', 'STRING', 'GOSI Registration Number for Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'commercialRegistration', '', 'STRING', 'Commercial Registration Number for Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'lmraNumber', '', 'STRING', 'LMRA Registration Number', 'BHR', 1, 1);

-- Bahrain Leave Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'annualLeaveDays', '30', 'NUMBER', 'Annual leave days in Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'sickLeaveDays', '15', 'NUMBER', 'Sick leave days in Bahrain (paid)', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'maternityLeaveDays', '60', 'NUMBER', 'Maternity leave days in Bahrain', 'BHR', 1, 1);

-- ================================
-- QATAR Settings
-- ================================

-- Qatar General Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'currency', 'QAR', 'STRING', 'Qatari Riyal currency code', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payFrequency', 'MONTHLY', 'STRING', 'Pay frequency for Qatar employees', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payDay', '25', 'NUMBER', 'Default pay day for Qatar', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingDaysPerWeek', '6', 'NUMBER', 'Working days per week in Qatar', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingHoursPerDay', '8', 'NUMBER', 'Standard working hours per day in Qatar', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'ramadanWorkingHours', '6', 'NUMBER', 'Working hours during Ramadan in Qatar', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeEnabled', 'true', 'BOOLEAN', 'Overtime calculation enabled for Qatar', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeRate', '1.25', 'NUMBER', 'Qatar regular overtime rate (125%)', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'restDayOvertimeRate', '1.5', 'NUMBER', 'Qatar rest day overtime rate (150%)', 'QAT', 1, 1);

-- Qatar Compliance Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'wpsEnabled', 'true', 'BOOLEAN', 'ADLSA WPS enabled for Qatar', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'adlsaEstablishmentId', '', 'STRING', 'ADLSA Establishment ID', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'commercialRegistration', '', 'STRING', 'Commercial Registration Number for Qatar', 'QAT', 1, 1);

-- Qatar Leave Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'annualLeaveDays', '21', 'NUMBER', 'Annual leave days in Qatar (increases with service)', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'sickLeaveDays', '15', 'NUMBER', 'Sick leave days in Qatar (paid)', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'maternityLeaveDays', '50', 'NUMBER', 'Maternity leave days in Qatar', 'QAT', 1, 1);

-- ================================
-- EGYPT Settings
-- ================================

-- Egypt General Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'currency', 'EGP', 'STRING', 'Egyptian Pound currency code', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payFrequency', 'MONTHLY', 'STRING', 'Pay frequency for Egypt employees', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'payDay', '25', 'NUMBER', 'Default pay day for Egypt', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingDaysPerWeek', '6', 'NUMBER', 'Working days per week in Egypt', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'workingHoursPerDay', '8', 'NUMBER', 'Standard working hours per day in Egypt', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'ramadanWorkingHours', '6', 'NUMBER', 'Working hours during Ramadan in Egypt', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'overtimeEnabled', 'true', 'BOOLEAN', 'Overtime calculation enabled for Egypt', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'daytimeOvertimeRate', '1.35', 'NUMBER', 'Egypt daytime overtime rate (135%)', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('general', 'nighttimeOvertimeRate', '1.7', 'NUMBER', 'Egypt nighttime overtime rate (170%)', 'EGY', 1, 1);

-- Egypt Compliance Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'socialInsuranceNumber', '', 'STRING', 'Social Insurance Registration Number', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'commercialRegistration', '', 'STRING', 'Commercial Registration Number for Egypt', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('compliance', 'taxRegistrationNumber', '', 'STRING', 'Tax Registration Number', 'EGY', 1, 1);

-- Egypt Leave Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'annualLeaveDays', '21', 'NUMBER', 'Annual leave days in Egypt', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'sickLeaveDays', '30', 'NUMBER', 'Sick leave days in Egypt', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('leave', 'maternityLeaveDays', '90', 'NUMBER', 'Maternity leave days in Egypt', 'EGY', 1, 1);

-- ================================
-- COMMON AIR TICKET SETTINGS FOR GCC COUNTRIES
-- ================================

-- UAE Air Ticket Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'enabled', 'true', 'BOOLEAN', 'Air ticket allowance enabled for UAE', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'frequency', 'BIENNIAL', 'STRING', 'Air ticket frequency (every 2 years)', 'UAE', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'defaultSegment', 'ECONOMY', 'STRING', 'Default air ticket segment', 'UAE', 1, 1);

-- Saudi Air Ticket Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'enabled', 'true', 'BOOLEAN', 'Air ticket allowance enabled for Saudi Arabia', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'frequency', 'BIENNIAL', 'STRING', 'Air ticket frequency (every 2 years)', 'SAU', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'defaultSegment', 'ECONOMY', 'STRING', 'Default air ticket segment', 'SAU', 1, 1);

-- Oman Air Ticket Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'enabled', 'true', 'BOOLEAN', 'Air ticket allowance enabled for Oman', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'frequency', 'BIENNIAL', 'STRING', 'Air ticket frequency (every 2 years)', 'OMN', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'defaultSegment', 'ECONOMY', 'STRING', 'Default air ticket segment', 'OMN', 1, 1);

-- Bahrain Air Ticket Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'enabled', 'true', 'BOOLEAN', 'Air ticket allowance enabled for Bahrain', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'frequency', 'BIENNIAL', 'STRING', 'Air ticket frequency (every 2 years)', 'BHR', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'defaultSegment', 'ECONOMY', 'STRING', 'Default air ticket segment', 'BHR', 1, 1);

-- Qatar Air Ticket Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'enabled', 'true', 'BOOLEAN', 'Air ticket allowance enabled for Qatar', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'frequency', 'BIENNIAL', 'STRING', 'Air ticket frequency (every 2 years)', 'QAT', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'defaultSegment', 'ECONOMY', 'STRING', 'Default air ticket segment', 'QAT', 1, 1);

-- Egypt Air Ticket Settings
INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'enabled', 'true', 'BOOLEAN', 'Air ticket allowance enabled for Egypt', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'frequency', 'BIENNIAL', 'STRING', 'Air ticket frequency (every 2 years)', 'EGY', 1, 1);

INSERT INTO HRMS_PAYROLL_SETTINGS (SECTION, SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, PAYROLL_COUNTRY, IS_ACTIVE, CREATED_BY) 
VALUES ('airTicket', 'defaultSegment', 'ECONOMY', 'STRING', 'Default air ticket segment', 'EGY', 1, 1);

-- Final Commit
COMMIT;

-- ================================
-- VERIFICATION QUERIES
-- ================================

-- Count records by country
SELECT 'Total Settings Count' as INFO, COUNT(*) as COUNT FROM HRMS_PAYROLL_SETTINGS;

SELECT 'Settings by Country' as INFO, PAYROLL_COUNTRY, COUNT(*) as COUNT 
FROM HRMS_PAYROLL_SETTINGS 
GROUP BY PAYROLL_COUNTRY 
ORDER BY PAYROLL_COUNTRY;

SELECT 'Settings by Section and Country' as INFO, PAYROLL_COUNTRY, SECTION, COUNT(*) as COUNT 
FROM HRMS_PAYROLL_SETTINGS 
GROUP BY PAYROLL_COUNTRY, SECTION 
ORDER BY PAYROLL_COUNTRY, SECTION;

-- Verify specific countries
SELECT 'UAE Settings' as INFO, SECTION, SETTING_KEY, SETTING_VALUE 
FROM HRMS_PAYROLL_SETTINGS 
WHERE PAYROLL_COUNTRY = 'UAE' 
ORDER BY SECTION, SETTING_KEY;

SELECT 'Saudi Settings' as INFO, SECTION, SETTING_KEY, SETTING_VALUE 
FROM HRMS_PAYROLL_SETTINGS 
WHERE PAYROLL_COUNTRY = 'SAU' 
ORDER BY SECTION, SETTING_KEY;

-- Check all countries have currency settings
SELECT 'Currency Settings Check' as INFO, PAYROLL_COUNTRY, SETTING_VALUE as CURRENCY 
FROM HRMS_PAYROLL_SETTINGS 
WHERE SETTING_KEY = 'currency' 
ORDER BY PAYROLL_COUNTRY;
