-- Multi-Country Payroll System Deployment Script
-- Execute these commands manually in your Oracle SQL client

-- Step 1: Create Countries Table
CREATE TABLE HRMS_COUNTRIES (
  COUNTRY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COUNTRY_CODE VARCHAR2(3) UNIQUE NOT NULL,
  COUNTRY_NAME VARCHAR2(100) NOT NULL,
  CURRENCY_CODE VARCHAR2(3) NOT NULL,
  CURRENCY_SYMBOL VARCHAR2(10) NOT NULL,
  CURRENCY_DECIMALS NUMBER(1) DEFAULT 2,
  IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
  WPS_ENABLED NUMBER(1) DEFAULT 0 CHECK (WPS_ENABLED IN (0, 1)),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Step 2: Create Payroll Country Policies Table
CREATE TABLE HRMS_PAYROLL_COUNTRY_POLICIES (
  POLICY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COUNTRY_CODE VARCHAR2(3) NOT NULL,
  POLICY_CATEGORY VARCHAR2(50) NOT NULL,
  POLICY_NAME VARCHAR2(100) NOT NULL,
  POLICY_TYPE VARCHAR2(30) NOT NULL,
  EMPLOYEE_RATE NUMBER(7,4),
  EMPLOYER_RATE NUMBER(7,4),
  FIXED_AMOUNT NUMBER(15,2),
  CAP_AMOUNT NUMBER(15,2),
  MIN_THRESHOLD NUMBER(15,2),
  MAX_THRESHOLD NUMBER(15,2),
  CALCULATION_BASE VARCHAR2(50),
  CONDITIONS VARCHAR2(1000),
  IS_MANDATORY NUMBER(1) DEFAULT 1,
  IS_ACTIVE NUMBER(1) DEFAULT 1,
  EFFECTIVE_FROM DATE DEFAULT SYSDATE,
  EFFECTIVE_TO DATE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Step 3: Create Air Ticket Accruals Table
CREATE TABLE HRMS_AIR_TICKET_ACCRUALS (
  ACCRUAL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPLOYEE_ID NUMBER NOT NULL,
  ACCRUAL_YEAR NUMBER(4) NOT NULL,
  ACCRUAL_MONTH NUMBER(2) NOT NULL,
  MONTHLY_ACCRUAL_AMOUNT NUMBER(15,2) NOT NULL,
  TOTAL_ACCRUED_AMOUNT NUMBER(15,2) NOT NULL,
  TICKET_SEGMENT VARCHAR2(20),
  ESTIMATED_TICKET_COST NUMBER(15,2),
  UTILIZATION_DATE DATE,
  UTILIZED_AMOUNT NUMBER(15,2) DEFAULT 0,
  STATUS VARCHAR2(20) DEFAULT 'ACCRUED' CHECK (STATUS IN ('ACCRUED', 'PARTIALLY_UTILIZED', 'FULLY_UTILIZED', 'EXPIRED')),
  FIFO_SEQUENCE NUMBER,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UK_EMP_ACCRUAL_PERIOD UNIQUE (EMPLOYEE_ID, ACCRUAL_YEAR, ACCRUAL_MONTH)
);

-- Step 4: Create Statutory Deductions Table
CREATE TABLE HRMS_STATUTORY_DEDUCTIONS (
  DEDUCTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPLOYEE_ID NUMBER NOT NULL,
  PAYROLL_PERIOD_ID NUMBER,
  COUNTRY_CODE VARCHAR2(3) NOT NULL,
  DEDUCTION_TYPE VARCHAR2(50) NOT NULL,
  DEDUCTION_NAME VARCHAR2(100) NOT NULL,
  CALCULATION_BASE NUMBER(15,2) NOT NULL,
  EMPLOYEE_AMOUNT NUMBER(15,2) DEFAULT 0,
  EMPLOYER_AMOUNT NUMBER(15,2) DEFAULT 0,
  TOTAL_AMOUNT NUMBER(15,2) NOT NULL,
  PAYMENT_STATUS VARCHAR2(20) DEFAULT 'PENDING',
  PAYMENT_DATE DATE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Step 5: Create Gratuity Accruals Table
CREATE TABLE HRMS_GRATUITY_ACCRUALS (
  GRATUITY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPLOYEE_ID NUMBER NOT NULL,
  ACCRUAL_YEAR NUMBER(4) NOT NULL,
  ACCRUAL_MONTH NUMBER(2) NOT NULL,
  SERVICE_YEARS NUMBER(5,2) NOT NULL,
  SERVICE_MONTHS NUMBER(3) NOT NULL,
  MONTHLY_ACCRUAL_AMOUNT NUMBER(15,2) NOT NULL,
  TOTAL_ACCRUED_AMOUNT NUMBER(15,2) NOT NULL,
  CALCULATION_BASE_SALARY NUMBER(15,2) NOT NULL,
  GRATUITY_RATE_DAYS NUMBER(5,2) NOT NULL,
  COUNTRY_CODE VARCHAR2(3) NOT NULL,
  PAYMENT_STATUS VARCHAR2(20) DEFAULT 'ACCRUED',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UK_GRATUITY_PERIOD UNIQUE (EMPLOYEE_ID, ACCRUAL_YEAR, ACCRUAL_MONTH)
);

-- Step 6: Create CTC Calculation History Table
CREATE TABLE HRMS_CTC_CALCULATION_HISTORY (
  CALCULATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPLOYEE_ID NUMBER,
  CALCULATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  COUNTRY_CODE VARCHAR2(3) NOT NULL,
  EMPLOYEE_TYPE VARCHAR2(20),
  NATIONALITY VARCHAR2(50),
  GROSS_SALARY NUMBER(15,2) NOT NULL,
  BASIC_SALARY NUMBER(15,2) NOT NULL,
  NET_SALARY NUMBER(15,2) NOT NULL,
  EMPLOYEE_DEDUCTIONS NUMBER(15,2) NOT NULL,
  EMPLOYER_CONTRIBUTIONS NUMBER(15,2) NOT NULL,
  GRATUITY_ACCRUAL NUMBER(15,2) NOT NULL,
  AIR_TICKET_ACCRUAL NUMBER(15,2) NOT NULL,
  MONTHLY_CTC NUMBER(15,2) NOT NULL,
  ANNUAL_CTC NUMBER(15,2) NOT NULL,
  CALCULATION_VERSION VARCHAR2(10) DEFAULT '1.0'
);

-- Step 7: Add columns to existing HRMS_EMPLOYEES table
ALTER TABLE HRMS_EMPLOYEES ADD PAYROLL_COUNTRY VARCHAR2(3) DEFAULT 'IND';
ALTER TABLE HRMS_EMPLOYEES ADD EMPLOYEE_TYPE VARCHAR2(20) DEFAULT 'EXPATRIATE';
ALTER TABLE HRMS_EMPLOYEES ADD AIR_TICKET_ELIGIBLE NUMBER(1) DEFAULT 0;
ALTER TABLE HRMS_EMPLOYEES ADD TICKET_SEGMENT VARCHAR2(20) DEFAULT 'ECONOMY';
ALTER TABLE HRMS_EMPLOYEES ADD ESTIMATED_TICKET_COST NUMBER(15,2);
ALTER TABLE HRMS_EMPLOYEES ADD NATIONALITY VARCHAR2(50);

-- Step 8: Add column to existing HRMS_PAYROLL_SETTINGS table
ALTER TABLE HRMS_PAYROLL_SETTINGS ADD PAYROLL_COUNTRY VARCHAR2(3) DEFAULT 'IND';

-- Step 9: Insert Countries Data
INSERT INTO HRMS_COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_SYMBOL, CURRENCY_DECIMALS, IS_ACTIVE, WPS_ENABLED) VALUES ('IND', 'India', 'INR', '₹', 2, 1, 0);
INSERT INTO HRMS_COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_SYMBOL, CURRENCY_DECIMALS, IS_ACTIVE, WPS_ENABLED) VALUES ('UAE', 'United Arab Emirates', 'AED', 'د.إ', 2, 1, 1);
INSERT INTO HRMS_COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_SYMBOL, CURRENCY_DECIMALS, IS_ACTIVE, WPS_ENABLED) VALUES ('SAU', 'Saudi Arabia', 'SAR', 'ر.س', 2, 1, 1);
INSERT INTO HRMS_COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_SYMBOL, CURRENCY_DECIMALS, IS_ACTIVE, WPS_ENABLED) VALUES ('OMN', 'Oman', 'OMR', 'ر.ع.', 3, 1, 1);
INSERT INTO HRMS_COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_SYMBOL, CURRENCY_DECIMALS, IS_ACTIVE, WPS_ENABLED) VALUES ('BHR', 'Bahrain', 'BHD', 'د.ب', 3, 1, 1);
INSERT INTO HRMS_COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_SYMBOL, CURRENCY_DECIMALS, IS_ACTIVE, WPS_ENABLED) VALUES ('QAT', 'Qatar', 'QAR', 'ر.ق', 2, 1, 1);
INSERT INTO HRMS_COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, CURRENCY_CODE, CURRENCY_SYMBOL, CURRENCY_DECIMALS, IS_ACTIVE, WPS_ENABLED) VALUES ('EGY', 'Egypt', 'EGP', '£', 2, 1, 0);

-- Step 10: Insert Indian Policies
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, IS_MANDATORY) VALUES ('IND', 'SOCIAL_SECURITY', 'PF_EMPLOYEE', 'PERCENTAGE', 12.0, 0.0, 'BASIC', 15000, 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, IS_MANDATORY) VALUES ('IND', 'SOCIAL_SECURITY', 'PF_EMPLOYER', 'PERCENTAGE', 0.0, 12.0, 'BASIC', 15000, 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, MAX_THRESHOLD, IS_MANDATORY) VALUES ('IND', 'SOCIAL_SECURITY', 'ESI_EMPLOYEE', 'PERCENTAGE', 0.75, 0.0, 'GROSS', 21000, 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, MAX_THRESHOLD, IS_MANDATORY) VALUES ('IND', 'SOCIAL_SECURITY', 'ESI_EMPLOYER', 'PERCENTAGE', 0.0, 3.25, 'GROSS', 21000, 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, IS_MANDATORY) VALUES ('IND', 'SOCIAL_SECURITY', 'EPS_EMPLOYER', 'PERCENTAGE', 0.0, 8.33, 'BASIC', 15000, 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, IS_MANDATORY) VALUES ('IND', 'SOCIAL_SECURITY', 'EDLI_EMPLOYER', 'PERCENTAGE', 0.0, 0.5, 'BASIC', 15000, 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, CONDITIONS, IS_MANDATORY) VALUES ('IND', 'GRATUITY', 'GRATUITY_ACCRUAL', 'DAYS', 15, 'BASIC', 'SERVICE_YEARS>=5', 1);

-- Step 11: Insert UAE Policies
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('UAE', 'SOCIAL_SECURITY', 'GPSSA_EMPLOYEE', 'PERCENTAGE', 5.0, 0.0, 'GROSS', 50000, 'NATIONALITY=EMIRATI', 0);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('UAE', 'SOCIAL_SECURITY', 'GPSSA_EMPLOYER', 'PERCENTAGE', 0.0, 12.5, 'GROSS', 50000, 'NATIONALITY=EMIRATI', 0);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, CONDITIONS, IS_MANDATORY) VALUES ('UAE', 'GRATUITY', 'EOSB_FIRST_5_YEARS', 'DAYS', 21, 'BASIC', 'SERVICE_YEARS<=5', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, CONDITIONS, IS_MANDATORY) VALUES ('UAE', 'GRATUITY', 'EOSB_AFTER_5_YEARS', 'DAYS', 30, 'BASIC', 'SERVICE_YEARS>5', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, CONDITIONS, IS_MANDATORY) VALUES ('UAE', 'AIR_TICKET', 'BIENNIAL_ALLOWANCE', 'AMOUNT', 100, 'ESTIMATED_COST', 'ELIGIBLE=YES', 0);

-- Step 12: Insert Saudi Arabia Policies
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('SAU', 'SOCIAL_SECURITY', 'GOSI_EMPLOYEE_SAUDI', 'PERCENTAGE', 10.0, 0.0, 'GROSS', 45000, 'NATIONALITY=SAUDI', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('SAU', 'SOCIAL_SECURITY', 'GOSI_EMPLOYER_SAUDI', 'PERCENTAGE', 0.0, 12.0, 'GROSS', 45000, 'NATIONALITY=SAUDI', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('SAU', 'SOCIAL_SECURITY', 'GOSI_EMPLOYEE_EXPAT', 'PERCENTAGE', 2.0, 0.0, 'GROSS', 45000, 'NATIONALITY!=SAUDI', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('SAU', 'SOCIAL_SECURITY', 'GOSI_EMPLOYER_EXPAT', 'PERCENTAGE', 0.0, 2.0, 'GROSS', 45000, 'NATIONALITY!=SAUDI', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, CONDITIONS, IS_MANDATORY) VALUES ('SAU', 'GRATUITY', 'EOSB_FIRST_5_YEARS', 'MONTHS', 0.5, 'BASIC_ALLOWANCES', 'SERVICE_YEARS<=5', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, CONDITIONS, IS_MANDATORY) VALUES ('SAU', 'GRATUITY', 'EOSB_AFTER_5_YEARS', 'MONTHS', 1.0, 'BASIC_ALLOWANCES', 'SERVICE_YEARS>5', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, CONDITIONS, IS_MANDATORY) VALUES ('SAU', 'AIR_TICKET', 'BIENNIAL_ALLOWANCE', 'AMOUNT', 100, 'ESTIMATED_COST', 'ELIGIBLE=YES', 0);

-- Step 13: Insert Other Countries Policies
-- Oman
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('OMN', 'SOCIAL_SECURITY', 'PASI_EMPLOYEE', 'PERCENTAGE', 7.0, 0.0, 'GROSS', 6000, 'NATIONALITY=OMANI', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('OMN', 'SOCIAL_SECURITY', 'PASI_EMPLOYER', 'PERCENTAGE', 0.0, 10.5, 'GROSS', 6000, 'NATIONALITY=OMANI', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, IS_MANDATORY) VALUES ('OMN', 'GRATUITY', 'EOSB_ACCRUAL', 'MONTHS', 1.0, 'BASIC', 1);

-- Bahrain
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('BHR', 'SOCIAL_SECURITY', 'GOSI_EMPLOYEE', 'PERCENTAGE', 6.0, 0.0, 'GROSS', 5000, 'NATIONALITY=BAHRAINI', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, CAP_AMOUNT, CONDITIONS, IS_MANDATORY) VALUES ('BHR', 'SOCIAL_SECURITY', 'GOSI_EMPLOYER', 'PERCENTAGE', 0.0, 12.0, 'GROSS', 5000, 'NATIONALITY=BAHRAINI', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, IS_MANDATORY) VALUES ('BHR', 'GRATUITY', 'EOSB_ACCRUAL', 'MONTHS', 1.0, 'GROSS', 1);

-- Qatar
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, CONDITIONS, IS_MANDATORY) VALUES ('QAT', 'GRATUITY', 'EOSB_ACCRUAL', 'WEEKS', 3.0, 'BASIC', 'SERVICE_YEARS>=1', 1);

-- Egypt
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, IS_MANDATORY) VALUES ('EGY', 'SOCIAL_SECURITY', 'SOCIAL_INSURANCE_EMPLOYEE', 'PERCENTAGE', 14.0, 0.0, 'GROSS', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYEE_RATE, EMPLOYER_RATE, CALCULATION_BASE, IS_MANDATORY) VALUES ('EGY', 'SOCIAL_SECURITY', 'SOCIAL_INSURANCE_EMPLOYER', 'PERCENTAGE', 0.0, 26.0, 'GROSS', 1);
INSERT INTO HRMS_PAYROLL_COUNTRY_POLICIES (COUNTRY_CODE, POLICY_CATEGORY, POLICY_NAME, POLICY_TYPE, EMPLOYER_RATE, CALCULATION_BASE, IS_MANDATORY) VALUES ('EGY', 'GRATUITY', 'EOSB_ACCRUAL', 'MONTHS', 1.0, 'GROSS', 1);

-- Step 14: Create Performance Indexes
CREATE INDEX IDX_EMPLOYEES_PAYROLL_COUNTRY ON HRMS_EMPLOYEES(PAYROLL_COUNTRY);
CREATE INDEX IDX_EMPLOYEES_EMPLOYEE_TYPE ON HRMS_EMPLOYEES(EMPLOYEE_TYPE);
CREATE INDEX IDX_EMPLOYEES_NATIONALITY ON HRMS_EMPLOYEES(NATIONALITY);
CREATE INDEX IDX_AIR_TICKET_ACCRUALS_EMP ON HRMS_AIR_TICKET_ACCRUALS(EMPLOYEE_ID);
CREATE INDEX IDX_AIR_TICKET_ACCRUALS_STATUS ON HRMS_AIR_TICKET_ACCRUALS(STATUS);
CREATE INDEX IDX_STATUTORY_DEDUCTIONS_EMP ON HRMS_STATUTORY_DEDUCTIONS(EMPLOYEE_ID);
CREATE INDEX IDX_GRATUITY_ACCRUALS_EMP ON HRMS_GRATUITY_ACCRUALS(EMPLOYEE_ID);
CREATE INDEX IDX_CTC_HISTORY_EMP ON HRMS_CTC_CALCULATION_HISTORY(EMPLOYEE_ID);
CREATE INDEX IDX_PAYROLL_POLICIES_COUNTRY ON HRMS_PAYROLL_COUNTRY_POLICIES(COUNTRY_CODE, IS_ACTIVE);

-- Step 15: Update existing employees with default country
UPDATE HRMS_EMPLOYEES 
SET PAYROLL_COUNTRY = 'IND',
    EMPLOYEE_TYPE = 'EXPATRIATE',
    NATIONALITY = 'INDIAN'
WHERE PAYROLL_COUNTRY IS NULL OR PAYROLL_COUNTRY = '';

-- Step 16: Commit all changes
COMMIT;

-- Verification Queries
SELECT 'Countries Created' as STATUS, COUNT(*) as COUNT FROM HRMS_COUNTRIES;
SELECT 'Policies Created' as STATUS, COUNT(*) as COUNT FROM HRMS_PAYROLL_COUNTRY_POLICIES;
SELECT 'Employees Updated' as STATUS, COUNT(*) as COUNT FROM HRMS_EMPLOYEES WHERE PAYROLL_COUNTRY IS NOT NULL;
